// Elephant Walk - All parts laid out in a line
// Auto-generated by: apothecary parts elephant-walk
//
// Parts are positioned using bounding boxes to prevent overlap.
// Parts: 11, Gap: 10mm

// Import STL files - positioned to avoid collisions
// calibration_cube (10.0 x 10.0 x 10.0 mm)
translate([0.00, -5.00, 0])
    import("calibration_cube/calibration_cube.stl");

// contranot (48.0 x 48.0 x 31.5 mm)
translate([44.00, -0.00, 0])
    import("contranot/contranot.stl");

// couch_block (152.4 x 101.6 x 50.8 mm)
translate([154.20, -50.80, 0])
    import("couch_block/couch_block.stl");

// dryerknob (33.0 x 33.0 x 20.0 mm)
translate([256.90, -0.00, 0])
    import("dryerknob/dryerknob.stl");

// fifel (25.0 x 200.0 x 25.4 mm)
translate([295.90, 100.00, 0])
    import("fifel/fifel.stl");

// footpedal (182.0 x 30.4 x 106.6 mm)
translate([319.40, -14.90, 0])
    import("footpedal/footpedal.stl");

// matboard_cutter_mount (20.0 x 19.9 x 10.0 mm)
translate([520.40, -13.97, 0])
    import("matboard_cutter_mount/matboard_cutter_mount.stl");

// parametric_star (27.1 x 28.5 x 3.0 mm)
translate([552.54, -0.00, 0])
    import("parametric_star/parametric_star.stl");

// solderfan (134.0 x 12.0 x 134.0 mm)
translate([577.54, 6.00, 0])
    import("solderfan/solderfan.stl");

// star_cookiecutter (58.3 x 61.1 x 11.0 mm)
translate([747.81, -0.00, 0])
    import("star_cookiecutter/star_cookiecutter.stl");

// v_slot (20.0 x 20.0 x 20.0 mm)
translate([799.81, -0.00, 0])
    import("v_slot/v_slot.stl");
