"""A scripted OrcaSlicer and the profiles beside it, for the slicer tests.

Kept out of ``conftest.py``, as the firmware fakes are (``firmware_helpers.py``):
``from conftest import ...`` is not a stable import.

The fake answers ``--help`` as OrcaSlicer 2.4.2 does (its version first), and a
slice by reading the profiles it is handed -- refusing, as OrcaSlicer does, a
process that is not for the machine's system profile -- and writing
``plate_1.gcode`` (a header, the start G-code's homing, a square of moves at the
process's layer height, OrcaSlicer's estimate comments and a config block) and
``result.json``. ``FAKE_ORCA`` in its environment scripts a failure: ``outside``
prints the error OrcaSlicer gives for a model off the bed and exits non-zero;
``silent`` exits zero and writes nothing; ``slow`` takes a minute first, for a
cancel to stop. Each argv is recorded beside it.
"""

from __future__ import annotations

import json
import stat
import sys
import textwrap
from pathlib import Path

FAKE_ORCASLICER = textwrap.dedent(r"""
    #!/usr/bin/env python3
    import json, os, sys
    from pathlib import Path
    args = sys.argv[1:]
    with open(__file__ + ".calls", "a") as f:
        f.write(json.dumps(args) + "\n")
    if not args or args[0] in ("--help", "-h"):
        Path("result.json").write_text('{"return_code": 0}')  # as OrcaSlicer does, wherever it runs
        print("OrcaSlicer-2.4.2:")
        print("Usage: orca-slicer [ OPTIONS ] [ file.3mf/file.stl ... ]")
        sys.exit(0)
    def opt(name):
        return args[args.index(name) + 1] if name in args else None
    out = Path(opt("--outputdir"))
    out.mkdir(parents=True, exist_ok=True)
    mode = os.environ.get("FAKE_ORCA", "")
    if mode == "silent":
        sys.exit(0)
    if mode == "slow":
        import time
        print("slicing slowly", flush=True)
        time.sleep(60)
    machine, process = [json.loads(Path(p).read_text()) for p in opt("--load-settings").split(";")]
    filament = json.loads(Path(opt("--load-filaments")).read_text())
    if machine.get("inherits") not in process.get("compatible_printers", []):
        print("process not compatible with printer.", file=sys.stderr)
        (out / "result.json").write_text(json.dumps({"return_code": -17, "error_string": "process not compatible with printer."}))
        sys.exit(239)
    if mode == "outside":
        print("[error] run found error, return -51, exit...", file=sys.stderr)
        print("Warning: the bed is small", file=sys.stderr)
        (out / "result.json").write_text(json.dumps({"return_code": -51,
            "error_string": "Some objects are located over the boundary of the heated bed.",
            "sliced_plates": []}))
        sys.exit(205)
    layer = float(process["layer_height"])
    loops = process.get("wall_loops")
    lines = ["; HEADER_BLOCK_START", "; generated by OrcaSlicer 2.4.2 (fake)",
             "; total layer number: 3", "; HEADER_BLOCK_END", "",
             "; EXECUTABLE_BLOCK_START", *machine.get("machine_start_gcode", "").splitlines(),
             "G90", "M83"]
    for n in range(1, 4):
        z = round(n * layer, 3)
        lines += [";LAYER_CHANGE", f"G1 Z{z} F600", "G1 X105 Y105 F3000",
                  "G1 X115 Y105 E0.5", "G1 X115 Y115 E0.5", "G1 X105 Y115 E0.5", "G1 X105 Y105 E0.5"]
    lines += ["G1 X5 Y176 F3000 ; present print", "M104 S0", "M140 S0", "M84 X Y E",
              "; EXECUTABLE_BLOCK_END", "",
              "; filament used [mm] = 263.81", "; filament used [cm3] = 0.63",
              "; filament used [g] = 0.79", "; total filament used [g] = 0.79",
              "; total layers count = 3",
              "; estimated printing time (normal mode) = 1h 2m 3s",
              "; estimated first layer printing time (normal mode) = 48s", "",
              "; CONFIG_BLOCK_START", f"; layer_height = {process['layer_height']}",
              f"; wall_loops = {loops}", f"; filament_type = {filament['filament_type'][0]}",
              "; CONFIG_BLOCK_END"]
    (out / "plate_1.gcode").write_text("\n".join(lines) + "\n")
    (out / "result.json").write_text(json.dumps({"return_code": 0, "error_string": "Success.",
        "sliced_plates": [{"id": 1, "warning_message": ""}]}))
    """).lstrip()


# The chain of OrcaSlicer's Creality profiles the ender3's profile names, cut down
# to what a slice reads: each child's values over its parent's.
CREALITY = {
    "machine": {
        "fdm_machine_common": {
            "type": "machine",
            "name": "fdm_machine_common",
            "from": "system",
            "nozzle_diameter": ["0.4"],
            "printable_height": "250",
            "gcode_flavor": "marlin",
            "max_layer_height": ["0.32"],
            "min_layer_height": ["0.08"],
        },
        "fdm_creality_common": {
            "type": "machine",
            "name": "fdm_creality_common",
            "inherits": "fdm_machine_common",
            "from": "system",
            "machine_start_gcode": "G90 ; use absolute coordinates\nM140 S60\nM104 S150\n"
            "G28 ; home all axis\nM190 S60\nM109 S220\nG1 Z0.28 F240",
        },
        "Creality Ender-3 0.4 nozzle": {
            "type": "machine",
            "name": "Creality Ender-3 0.4 nozzle",
            "inherits": "fdm_creality_common",
            "from": "system",
            "printable_area": ["0x0", "220x0", "220x220", "0x220"],
            "max_layer_height": ["0.36"],
        },
    },
    "process": {
        "fdm_process_common": {
            "type": "process",
            "name": "fdm_process_common",
            "from": "system",
            "wall_loops": "3",
            "top_shell_layers": "4",
        },
        "fdm_process_creality_common": {
            "type": "process",
            "name": "fdm_process_creality_common",
            "inherits": "fdm_process_common",
            "from": "system",
            "layer_height": "0.2",
            "initial_layer_print_height": "0.2",
            "bottom_shell_layers": "3",
            "sparse_infill_density": "15%",
            "enable_support": "0",
        },
        "0.20mm Standard @Creality Ender3": {
            "type": "process",
            "name": "0.20mm Standard @Creality Ender3",
            "inherits": "fdm_process_creality_common",
            "from": "system",
            "wall_loops": "2",
            "top_shell_layers": "7",
            "bottom_shell_layers": "5",
            "compatible_printers": ["Creality Ender-3 0.4 nozzle"],
        },
    },
    "filament": {
        "fdm_filament_pla": {
            "type": "filament",
            "name": "fdm_filament_pla",
            "from": "system",
            "filament_type": ["PLA"],
            "nozzle_temperature": ["220"],
            "nozzle_temperature_initial_layer": ["220"],
            "cool_plate_temp": ["60"],
            "cool_plate_temp_initial_layer": ["60"],
        },
        "Creality Generic PLA": {
            "type": "filament",
            "name": "Creality Generic PLA",
            "inherits": "fdm_filament_pla",
            "from": "system",
        },
    },
}


def write_profiles(resources: Path) -> Path:
    """OrcaSlicer's ``resources/profiles`` as it ships them: the vendor's index, and
    each profile in its folder."""
    profiles = resources / "profiles"
    folder = profiles / "Creality"
    index = {"name": "Creality", "machine_list": [], "process_list": [], "filament_list": []}
    for kind, named in CREALITY.items():
        (folder / kind).mkdir(parents=True, exist_ok=True)
        for name, data in named.items():
            (folder / kind / f"{name}.json").write_text(json.dumps(data), encoding="utf-8")
            index[f"{kind}_list"].append({"name": name, "sub_path": f"{kind}/{name}.json"})
    (profiles / "Creality.json").write_text(json.dumps(index), encoding="utf-8")
    return profiles


def write_fake_orcaslicer(folder: Path) -> Path:
    """The fake at ``folder/bin/orca-slicer`` (this interpreter running it), its
    profiles at ``folder/resources`` -- where OrcaSlicer itself looks, one level up."""
    program = folder / "bin" / "orca-slicer"
    program.parent.mkdir(parents=True, exist_ok=True)
    program.write_text(
        FAKE_ORCASLICER.replace("#!/usr/bin/env python3", f"#!{sys.executable}", 1),
        encoding="utf-8",
    )
    program.chmod(program.stat().st_mode | stat.S_IXUSR)
    write_profiles(folder / "resources")
    return program


def fake_calls(program: Path) -> list[list[str]]:
    log = program.with_name(program.name + ".calls")
    if not log.exists():
        return []
    return [json.loads(line) for line in log.read_text().splitlines() if line.strip()]
