from apothecary.example import create_example_scene
from apothecary.templates import TemplateRenderer


def test_template_renderer_uses_context():
    scene = create_example_scene()
    tpl = "// Name: {{ scene_name }} ({{ object_count }})\n{{ scene_code }}"
    r = TemplateRenderer()
    out = r.render_scene_template(scene, tpl)
    assert f"Name: {scene.name}" in out
    assert "// Generated by OpenSCAD Framework" in out
