from click.testing import CliRunner

from apothecary.cli import cli


def test_parts_list():
    r = CliRunner().invoke(cli, ["parts", "list"])
    assert r.exit_code == 0
    # Should list at least one known part name
    assert "parametric_star" in r.output or "solderfan" in r.output


def test_parts_list_from_another_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    r = CliRunner().invoke(cli, ["parts", "list"])
    assert r.exit_code == 0
    assert "solderfan" in r.output


def test_parts_render_uses_the_repository_template_from_another_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    r = CliRunner().invoke(cli, ["parts", "render", "parametric_star", "-o", "p.scad"])
    assert r.exit_code == 0, r.output
    assert (tmp_path / "p.scad").read_text().startswith("// Generated by Apothecary")


def test_parts_info_json():
    r = CliRunner().invoke(cli, ["parts", "info", "parametric_star", "--json-out"])
    assert r.exit_code == 0
    assert '"name"' in r.output
    assert "parametric_star" in r.output


def test_an_unknown_parameter_for_a_part_without_a_model_is_a_clean_error():
    from click.testing import CliRunner

    from apothecary.cli import cli

    result = CliRunner().invoke(cli, ["parts", "generate-stl", "couch_block", "-p", "nope=1"])
    assert result.exit_code == 1
    assert "unknown parameter(s): nope" in result.output
    assert "Traceback" not in result.output
