from click.testing import CliRunner

from apothecary.cli import cli


def test_cli_system():
    runner = CliRunner()
    result = runner.invoke(cli, ["system"])
    assert result.exit_code == 0
    assert "Python" in result.output


def test_cli_testrun(tmp_path):
    runner = CliRunner()
    out = tmp_path / "ex.scad"
    result = runner.invoke(cli, ["testrun", "-o", str(out)])
    assert result.exit_code == 0
    assert out.exists()
    assert out.read_text().strip().startswith("// Generated by OpenSCAD Framework")
