import json

import pytest
from click.testing import CliRunner

from apothecary.cli import cli


def test_cli_system():
    runner = CliRunner()
    result = runner.invoke(cli, ["system"])
    assert result.exit_code == 0
    assert "Python" in result.output


def test_cli_check_includes_openscad_section():
    runner = CliRunner()
    result = runner.invoke(cli, ["check"])
    assert result.exit_code == 0
    assert "OpenSCAD:" in result.output


def test_cli_testrun(tmp_path):
    runner = CliRunner()
    out = tmp_path / "ex.scad"
    result = runner.invoke(cli, ["testrun", "-o", str(out)])
    assert result.exit_code == 0
    assert out.exists()
    assert out.read_text().strip().startswith("// Generated by OpenSCAD Framework")


def test_safe_echo_falls_back_on_a_legacy_code_page(monkeypatch):
    """Windows still defaults to cp1252, where writing "✓" raises.

    `check` used to die on its first line for that reason. The glyph is kept
    when the stream can carry it, so this drives the fallback directly rather
    than asserting the output is always ASCII.
    """
    from apothecary.cli import utils

    written = []

    def cp1252_secho(message, **style):
        message.encode("cp1252")  # raises exactly as a real console would
        written.append(message)

    monkeypatch.setattr(utils.click, "secho", cp1252_secho)
    utils._safe_echo("✓ Python: 3.11.12")
    utils._safe_echo("  ✗ OpenSCAD not found", fg="yellow")
    # cp1252 carries a bullet at 0x95, so this one never reaches the fallback.
    utils._safe_echo("    • datum-core")

    assert written == ["[OK] Python: 3.11.12", "  [X] OpenSCAD not found", "    • datum-core"]


def test_cli_check_runs_on_a_legacy_code_page(monkeypatch):
    """The whole command, not just the helper, survives the narrow encoding."""
    from apothecary.cli import utils

    monkeypatch.setattr(
        utils.click, "secho", lambda message, **style: message.encode("cp1252")
    )
    runner = CliRunner()
    result = runner.invoke(cli, ["check"], catch_exceptions=False)
    assert result.exit_code == 0


def test_cli_parts_info_reports_bounds():
    """A consumer sizing an assembly needs the envelope, not just a path."""
    runner = CliRunner()
    result = runner.invoke(cli, ["parts", "info", "datum-core", "--json-out"])
    assert result.exit_code == 0

    data = json.loads(result.output)
    assert data["bounds"] is not None
    assert data["bounds"]["size"] == pytest.approx({"x": 45.6, "y": 45.6, "z": 15.6})
