from click.testing import CliRunner

from apothecary.cli import cli


def test_parts_list():
    r = CliRunner().invoke(cli, ["parts", "list"])
    assert r.exit_code == 0
    # Should list at least one known part name
    assert "parametric_star" in r.output or "solderfan" in r.output


def test_parts_list_from_another_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    r = CliRunner().invoke(cli, ["parts", "list"])
    assert r.exit_code == 0
    assert "solderfan" in r.output


def test_parts_render_uses_the_repository_template_from_another_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    r = CliRunner().invoke(cli, ["parts", "render", "parametric_star", "-o", "p.scad"])
    assert r.exit_code == 0, r.output
    assert (tmp_path / "p.scad").read_text().startswith("// Generated by Apothecary")


def test_parts_info_json():
    r = CliRunner().invoke(cli, ["parts", "info", "parametric_star", "--json-out"])
    assert r.exit_code == 0
    assert '"name"' in r.output
    assert "parametric_star" in r.output
