from apothecary.example import create_example_scene


def test_example_scene_renders_header_and_objects():
    scene = create_example_scene()
    code = scene.render()
    assert "// Generated by OpenSCAD Framework v" in code
    assert "Scene: " in code
    assert "union()" in code or "difference()" in code
