import json
from pathlib import Path

from click.testing import CliRunner

from apothecary.cli import cli


def test_cli_validate_with_example_scene(tmp_path):
    # Use the example scene JSON written by testrun as a stand-in
    # Build a small scene JSON manually to avoid validation issues
    scene_json = {
        "name": "vtest",
        "objects": [{"type": "cube", "size": {"x": 1, "y": 2, "z": 3}, "center": False}],
    }
    f = tmp_path / "scene.json"
    f.write_text(json.dumps(scene_json), encoding="utf-8")

    r = CliRunner().invoke(cli, ["validate", "--scene-file", str(f)])
    assert r.exit_code == 0
    assert "Valid scene" in r.output


def test_cli_validate_rejects_missing_input():
    r = CliRunner().invoke(cli, ["validate"])
    assert r.exit_code != 0
    assert "No scene input provided" in r.output


def test_cli_templategenerate_inline(tmp_path):
    out = tmp_path / "templated.scad"
    tpl = "// {{ scene_name }}\n{{ scene_code }}"
    r = CliRunner().invoke(
        cli,
        [
            "templategenerate",
            "-t",
            tpl,
            "-o",
            str(out),
        ],
    )
    assert r.exit_code == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("// ") and "Generated by OpenSCAD Framework" in text


def test_cli_render_invalid_json(tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text("not-json", encoding="utf-8")
    r = CliRunner().invoke(cli, ["render", "--scene-file", str(bad)])
    assert r.exit_code != 0
    assert "Failed to parse scene JSON" in r.output


def test_cli_templategenerate_from_file(tmp_path):
    tpl_path = tmp_path / "basic.j2"
    tpl_path.write_text("// FileTpl: {{ scene_name }}\n{{ scene_code }}", encoding="utf-8")
    out = tmp_path / "templated2.scad"
    r = CliRunner().invoke(
        cli,
        [
            "templategenerate",
            "-t",
            f"@{tpl_path}",
            "-o",
            str(out),
        ],
    )
    assert r.exit_code == 0
    text = out.read_text(encoding="utf-8")
    assert text.startswith("// FileTpl:") and "Generated by OpenSCAD Framework" in text


def test_cli_parts_render_fallback_template(tmp_path):
    # Run in isolated FS so default template path is missing, forcing fallback include
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        out = Path("p.scad")
        r = runner.invoke(
            cli,
            [
                "parts",
                "render",
                "parametric_star",
                "-o",
                str(out),
            ],
        )
        assert r.exit_code == 0
        text = out.read_text(encoding="utf-8")
        assert text.strip().startswith("// ") and "include <" in text


def test_cli_parts_info_missing_wrapper_errors():
    r = CliRunner().invoke(cli, ["parts", "info", "nonexistent_part"])
    assert r.exit_code != 0
    assert "No wrapper module found" in r.output


def test_cli_inventory_templates_lists_templates():
    r = CliRunner().invoke(cli, ["inventory", "templates"])  # uses repo templates/
    assert r.exit_code == 0
    assert "template:" in r.output or "No templates found." in r.output


def test_cli_parts_render_refuses_to_overwrite_source(tmp_path):
    from apothecary.cli.utils import _load_part_wrapper

    src = _load_part_wrapper("parametric_star").DEFAULT.source_file
    before = src.read_bytes()
    r = CliRunner().invoke(cli, ["parts", "render", "parametric_star", "-o", str(src)])
    assert r.exit_code != 0
    assert "Refusing to overwrite" in r.output
    assert src.read_bytes() == before


def test_cli_parts_render_snowplow_uses_validated_params(tmp_path):
    out = tmp_path / "snowplow.scad"
    r = CliRunner().invoke(
        cli,
        [
            "parts",
            "render",
            "rc.snowplow",
            "--params-json",
            '{"blade_width": "200"}',
            "-o",
            str(out),
        ],
    )
    assert r.exit_code == 0, r.output
    text = out.read_text(encoding="utf-8")
    assert "200" in text and "cube" in text.lower()


def test_cli_parts_render_snowplow_rejects_bad_params(tmp_path):
    out = tmp_path / "snowplow.scad"
    r = CliRunner().invoke(
        cli,
        ["parts", "render", "rc.snowplow", "--params-json", '{"blade_width": -1}', "-o", str(out)],
    )
    assert r.exit_code != 0
    assert isinstance(r.exception, SystemExit)  # ClickException, not a pydantic traceback
    assert "Invalid parameters" in r.output
    assert not out.exists()
