import json

import pytest
from click.testing import CliRunner

from apothecary.cli import cli


def test_cli_system():
    runner = CliRunner()
    result = runner.invoke(cli, ["system"])
    assert result.exit_code == 0
    assert "Python" in result.output


def test_cli_check_includes_openscad_section():
    runner = CliRunner()
    result = runner.invoke(cli, ["check"])
    assert result.exit_code == 0
    assert "OpenSCAD:" in result.output


def test_cli_testrun(tmp_path):
    runner = CliRunner()
    out = tmp_path / "ex.scad"
    result = runner.invoke(cli, ["testrun", "-o", str(out)])
    assert result.exit_code == 0
    assert out.exists()
    assert out.read_text().strip().startswith("// Generated by OpenSCAD Framework")


def test_safe_echo_falls_back_on_a_legacy_code_page(monkeypatch):
    """Windows still defaults to cp1252, where writing "✓" raises.

    `check` used to die on its first line for that reason. The glyph is kept
    when the stream can carry it, so this drives the fallback directly rather
    than asserting the output is always ASCII.
    """
    from apothecary.cli import utils

    written = []

    def cp1252_secho(message, **style):
        message.encode("cp1252")  # raises exactly as a real console would
        written.append(message)

    monkeypatch.setattr(utils.click, "secho", cp1252_secho)
    utils._safe_echo("✓ Python: 3.11.12")
    utils._safe_echo("  ✗ OpenSCAD not found", fg="yellow")
    # cp1252 carries a bullet at 0x95, so this one never reaches the fallback.
    utils._safe_echo("    • datum_core")

    assert written == ["[OK] Python: 3.11.12", "  [X] OpenSCAD not found", "    • datum_core"]


def test_cli_check_runs_on_a_legacy_code_page(monkeypatch):
    """The whole command, not just the helper, survives the narrow encoding."""
    from apothecary.cli import utils

    monkeypatch.setattr(utils.click, "secho", lambda message, **style: message.encode("cp1252"))
    runner = CliRunner()
    result = runner.invoke(cli, ["check"], catch_exceptions=False)
    assert result.exit_code == 0


def test_cli_parts_info_reports_bounds():
    """A consumer sizing an assembly needs the envelope, not just a path."""
    runner = CliRunner()
    result = runner.invoke(cli, ["parts", "info", "datum_core", "--json-out"])
    assert result.exit_code == 0

    data = json.loads(result.output)
    assert data["bounds"] is not None
    assert data["bounds"]["size"] == pytest.approx({"x": 46.8, "y": 46.8, "z": 15.6})


@pytest.fixture
def uvicorn_runs(monkeypatch):
    from apothecary.cli import server

    calls = []
    monkeypatch.setattr(server.uvicorn, "run", lambda target, **kw: calls.append((target, kw)))
    return calls


def test_serve_listens_on_loopback_and_does_not_wait_on_open_streams(uvicorn_runs):
    result = CliRunner().invoke(cli, ["serve", "--no-viewer", "--port", "8123"])
    assert result.exit_code == 0, result.output
    [(target, kw)] = uvicorn_runs
    assert target == "apothecary.api:app"
    assert (kw["host"], kw["port"], kw["reload"]) == ("127.0.0.1", 8123, False)
    assert kw["timeout_graceful_shutdown"] == 3


def test_serve_refuses_an_address_off_this_machine(uvicorn_runs):
    result = CliRunner().invoke(cli, ["serve", "--host", "0.0.0.0"])
    assert result.exit_code == 1
    assert "this machine only" in result.output
    assert uvicorn_runs == []


RETIRED = {
    "install": (["install", "--no-viewer"], "nothing to install: three.js is vendored"),
}


@pytest.mark.parametrize("name", sorted(RETIRED))
def test_a_retired_command_names_its_replacement_and_fails(name):
    """Old options are swallowed, so a script reaches the pointer, not a usage error."""
    argv, instead = RETIRED[name]
    result = CliRunner().invoke(cli, argv)
    assert result.exit_code == 1
    assert instead in result.output


def test_retired_commands_are_not_listed():
    listing = CliRunner().invoke(cli, ["--help"]).output.split("Commands:")[1]
    listed = {line.split()[0] for line in listing.splitlines() if line.strip()}
    assert "check" in listed
    assert not set(RETIRED) & listed
