"""JSCAD renderer: a scene as a JavaScript module for @jscad/modeling v2.

The module exports ``main``, returning the scene's geometry built with the
functional API. OpenSCAD and JSCAD disagree on three things, and each is
translated here rather than left to the reader:

- angles: OpenSCAD takes degrees, JSCAD radians; a scalar ``rotate(a)`` is
  about Z, and ``rotate(a, v)`` is about the axis ``v``;
- centring: JSCAD centres every primitive on the origin, OpenSCAD puts a
  cube's corner and a cylinder's base there unless ``center=true``;
- a cone: OpenSCAD's ``cylinder(r1, r2)`` is JSCAD's ``cylinderElliptic``.
"""

from __future__ import annotations

import math

from .booleans import Difference, Hull, Intersection, Union
from .core import OpenSCADObject
from .models.vectors import Vector3D
from .primitives import Cube, Cylinder, Import, Sphere
from .scene import Scene
from .transforms import Rotate, Scale, Translate

HEADER = """// Generated by Apothecary -> JSCAD (@jscad/modeling v2)
import { cuboid, sphere, cylinder, cylinderElliptic } from '@jscad/modeling/src/primitives'
import { union, difference, intersection } from '@jscad/modeling/src/booleans'
import { hull } from '@jscad/modeling/src/operations/hulls'
import { translate, rotate, scale, transform } from '@jscad/modeling/src/transforms'
import { mat4 } from '@jscad/modeling/src/maths'

"""

BOOLEANS = {Union: "union", Difference: "difference", Intersection: "intersection", Hull: "hull"}


def _arr(values) -> str:
    return "[" + ", ".join(str(v) for v in values) + "]"


def _vec(v: Vector3D) -> str:
    return _arr((v.x, v.y, v.z))


def _children(obj) -> str:
    return ", ".join(_render_node(c) for c in obj.children)


def _render_node(obj: OpenSCADObject) -> str:
    if isinstance(obj, Cube):
        size = (
            obj.size
            if isinstance(obj.size, Vector3D)
            else Vector3D(x=obj.size, y=obj.size, z=obj.size)
        )
        centre = (0, 0, 0) if obj.center else (size.x / 2, size.y / 2, size.z / 2)
        return f"cuboid({{ size: {_vec(size)}, center: {_arr(centre)} }})"

    if isinstance(obj, Sphere):
        segments = f", segments: {obj.fn}" if obj.fn else ""
        return f"sphere({{ radius: {obj.r}{segments} }})"

    if isinstance(obj, Cylinder):
        r1, r2 = obj.radii()
        centre = _arr((0, 0, 0 if obj.center else obj.h / 2))
        segments = f", segments: {obj.fn}" if obj.fn else ""
        if r1 == r2:
            return f"cylinder({{ height: {obj.h}, radius: {r1}, center: {centre}{segments} }})"
        return (
            f"cylinderElliptic({{ height: {obj.h}, startRadius: {_arr((r1, r1))}, "
            f"endRadius: {_arr((r2, r2))}, center: {centre}{segments} }})"
        )

    if isinstance(obj, Import):
        # JSCAD builds geometry in code and has no import(): the mesh stands in
        # as the box it fits, so a site holding one still renders.
        try:
            box = obj.bounds()
        except Exception:  # a file not there yet, or not a mesh
            return f"[] /* import {obj.file!r}: not read */"
        lo, hi = box.min_point, box.max_point
        size = _arr((hi.x - lo.x, hi.y - lo.y, hi.z - lo.z))
        centre = _arr(((lo.x + hi.x) / 2, (lo.y + hi.y) / 2, (lo.z + hi.z) / 2))
        return f"cuboid({{ size: {size}, center: {centre} }}) /* import {obj.file!r}: its bounds */"

    for kind, name in BOOLEANS.items():
        if isinstance(obj, kind):
            # JSCAD's booleans refuse no arguments; an empty one is nothing.
            return f"{name}({_children(obj)})" if obj.children else "[]"

    if isinstance(obj, Translate):
        return f"translate({_vec(obj.v)}, [{_children(obj)}])"

    if isinstance(obj, Rotate):
        if isinstance(obj.a, Vector3D):
            angles = _arr(math.radians(a) for a in (obj.a.x, obj.a.y, obj.a.z))
            return f"rotate({angles}, [{_children(obj)}])"
        if obj.v is not None:
            matrix = f"mat4.fromRotation(mat4.create(), {math.radians(obj.a)}, {_vec(obj.v)})"
            return f"transform({matrix}, [{_children(obj)}])"
        return f"rotate({_arr((0, 0, math.radians(obj.a)))}, [{_children(obj)}])"

    if isinstance(obj, Scale):
        return f"scale({_vec(obj.v)}, [{_children(obj)}])"

    raise TypeError(f"Unsupported object type for JSCAD rendering: {type(obj)!r}")


class JSCADRenderer:
    """Render a :class:`Scene` into a JSCAD module string."""

    def render_scene(self, scene: Scene) -> str:
        geometries = ",\n    ".join(_render_node(obj) for obj in scene.objects)
        return HEADER + f"export const main = () => {{\n  return [\n    {geometries}\n  ]\n}}\n"
