import json
from pathlib import Path
from typing import List, Optional

from pydantic import BaseModel, Field, ValidationError

from .core import OpenSCADObject

try:  # optional version module for legacy compatibility
    from .version import __version__  # type: ignore
except ImportError:  # pragma: no cover
    __version__ = "0.1.0"


class Scene(BaseModel):
    """Top-level scene container"""

    objects: List[OpenSCADObject] = Field(default_factory=list)
    name: str = "untitled"
    version: str = __version__

    def render(self) -> str:
        """Render the entire scene to OpenSCAD code"""
        header = f"// Generated by OpenSCAD Framework v{self.version}\n"
        header += f"// Scene: {self.name}\n\n"

        objects_str = "\n\n".join(obj.render() for obj in self.objects)
        return header + objects_str

    def render_jscad(self) -> str:
        """Render the scene to a JSCAD JavaScript module string.

        This is a thin wrapper around :class:`JSCADRenderer` to provide
        a convenient API on the Scene model.
        """

        from .jscad import JSCADRenderer  # local import to avoid cycles

        return JSCADRenderer().render_scene(self)


class SceneLoadError(Exception):
    """Raised when a Scene cannot be loaded from JSON input."""


def load_scene_from_json(
    *,
    scene_file: Optional[Path] = None,
    scene_json: Optional[str] = None,
    allow_example_fallback: bool = True,
) -> Scene:
    """Load a ``Scene`` from a JSON file or JSON string.

    Priority:
    1. ``scene_json`` (raw JSON string)
    2. ``scene_file`` (path to JSON file)
    3. Example scene via :func:`create_example_scene` if ``allow_example_fallback`` is True.

    Raises :class:`SceneLoadError` on invalid JSON or failed validation.
    """

    if scene_json is not None and scene_file is not None:
        raise SceneLoadError("Provide only one of scene_json or scene_file, not both.")

    if scene_json is None and scene_file is None:
        if allow_example_fallback:
            # Lazily import here to avoid circular imports at module import time.
            from .example import create_example_scene  # type: ignore

            return create_example_scene()
        raise SceneLoadError("No scene input provided.")

    try:
        if scene_json is not None:
            data = json.loads(scene_json)
        else:
            assert scene_file is not None  # for type checkers
            data = json.loads(scene_file.read_text(encoding="utf-8"))
    except Exception as e:  # pragma: no cover - error path exercised via callers
        raise SceneLoadError(f"Failed to parse scene JSON: {e}") from e

    try:
        return Scene.model_validate(data)
    except ValidationError as e:  # pragma: no cover - error path exercised via callers
        raise SceneLoadError(f"Scene validation failed: {e}") from e
