// Generated by OpenSCAD Framework v0.1.0
// Scene: Garage

// Structure: workbench (Steel frame, pine top)
union() {
  // Substructure: frame_system
difference() {
  union() {
  translate([0.0, 0.0, 750.0]) {
  cube([1800.0, 600.0, 30.0], center=false);
}
  // Feature: leg_0
translate([50.0, 50.0, 0.0]) {
  cube([40.0, 40.0, 750.0], center=false);
}
  // Feature: leg_1
translate([1710.0, 50.0, 0.0]) {
  cube([40.0, 40.0, 750.0], center=false);
}
  // Feature: leg_2
translate([50.0, 510.0, 0.0]) {
  cube([40.0, 40.0, 750.0], center=false);
}
  // Feature: leg_3
translate([1710.0, 510.0, 0.0]) {
  cube([40.0, 40.0, 750.0], center=false);
}
}
  // Feature: cable_pass_through
translate([900.0, 550.0, 749.0]) {
  cylinder(h=32.0, r=15.0, center=false);
}
}
}

translate([100.0, 150.0, 780.0]) {
  // Structure: printer_1 (Aluminum extrusion + PETG)
union() {
  // Substructure: frame_system
union() {
  // Printer base / electronics enclosure
cube([300.0, 300.0, 50.0], center=false);
}
  // Substructure: gantry_system
union() {
  // Feature: left_post
translate([0.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: right_post
translate([280.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: gantry_bar
translate([0.0, 280.0, 380.0]) {
  cube([300.0, 20.0, 20.0], center=false);
}
}
}
}

translate([650.0, 150.0, 780.0]) {
  // Structure: printer_2 (Aluminum extrusion + PETG)
union() {
  // Substructure: frame_system
union() {
  // Printer base / electronics enclosure
cube([300.0, 300.0, 50.0], center=false);
}
  // Substructure: gantry_system
union() {
  // Feature: left_post
translate([0.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: right_post
translate([280.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: gantry_bar
translate([0.0, 280.0, 380.0]) {
  cube([300.0, 20.0, 20.0], center=false);
}
}
}
}

translate([1200.0, 150.0, 780.0]) {
  // Structure: printer_3 (Aluminum extrusion + PETG)
union() {
  // Substructure: frame_system
union() {
  // Printer base / electronics enclosure
cube([300.0, 300.0, 50.0], center=false);
}
  // Substructure: gantry_system
union() {
  // Feature: left_post
translate([0.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: right_post
translate([280.0, 280.0, 50.0]) {
  cube([20.0, 20.0, 330.0], center=false);
}
  // Feature: gantry_bar
translate([0.0, 280.0, 380.0]) {
  cube([300.0, 20.0, 20.0], center=false);
}
}
}
}