// Generated by Apothecary -> JSCAD
        import { cube, sphere, cylinder } from '@jscad/modeling/src/primitives'
        import { union, difference, intersection } from '@jscad/modeling/src/booleans'
        import { translate, rotate, scale } from '@jscad/modeling/src/transforms'

export const main = () => {
  return [
    union(difference(union(translate([0.0, 0.0, 750.0], [cube({ size: [1800.0, 600.0, 30.0], center: false })]), translate([50.0, 50.0, 0.0], [cube({ size: [40.0, 40.0, 750.0], center: false })]), translate([1710.0, 50.0, 0.0], [cube({ size: [40.0, 40.0, 750.0], center: false })]), translate([50.0, 510.0, 0.0], [cube({ size: [40.0, 40.0, 750.0], center: false })]), translate([1710.0, 510.0, 0.0], [cube({ size: [40.0, 40.0, 750.0], center: false })])), translate([900.0, 550.0, 749.0], [cylinder({ height: 32.0, radius: 15.0, center: false })]))),
    translate([100.0, 150.0, 780.0], [union(union(cube({ size: [300.0, 300.0, 50.0], center: false })), union(translate([0.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([280.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([0.0, 280.0, 380.0], [cube({ size: [300.0, 20.0, 20.0], center: false })])))]),
    translate([650.0, 150.0, 780.0], [union(union(cube({ size: [300.0, 300.0, 50.0], center: false })), union(translate([0.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([280.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([0.0, 280.0, 380.0], [cube({ size: [300.0, 20.0, 20.0], center: false })])))]),
    translate([1200.0, 150.0, 780.0], [union(union(cube({ size: [300.0, 300.0, 50.0], center: false })), union(translate([0.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([280.0, 280.0, 50.0], [cube({ size: [20.0, 20.0, 330.0], center: false })]), translate([0.0, 280.0, 380.0], [cube({ size: [300.0, 20.0, 20.0], center: false })])))])
  ]
}
