// Generated by Apothecary -> JSCAD
        import { cube, sphere, cylinder } from '@jscad/modeling/src/primitives'
        import { union, difference, intersection } from '@jscad/modeling/src/booleans'
        import { translate, rotate, scale } from '@jscad/modeling/src/transforms'

export const main = () => {
  return [
    union(difference(union(cube({ size: [100.0, 60.0, 4.0], center: false }), translate([6.0, 6.0, 4.0], [cylinder({ height: 6.0, radius: 4.0, center: false })]), translate([94.0, 6.0, 4.0], [cylinder({ height: 6.0, radius: 4.0, center: false })]), translate([6.0, 54.0, 4.0], [cylinder({ height: 6.0, radius: 4.0, center: false })]), translate([94.0, 54.0, 4.0], [cylinder({ height: 6.0, radius: 4.0, center: false })])), translate([6.0, 6.0, -1.0], [cylinder({ height: 12.0, radius: 1.7, center: false })]), translate([94.0, 6.0, -1.0], [cylinder({ height: 12.0, radius: 1.7, center: false })]), translate([6.0, 54.0, -1.0], [cylinder({ height: 12.0, radius: 1.7, center: false })]), translate([94.0, 54.0, -1.0], [cylinder({ height: 12.0, radius: 1.7, center: false })])), translate([20.0, 45.0, 0.0], [difference(union(cube({ size: [30.0, 10.0, 4.0], center: false })), translate([3.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]), translate([7.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]), translate([11.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]), translate([15.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]), translate([19.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]), translate([23.0, 5.0, -1.0], [cylinder({ height: 6.0, radius: 1.45, center: false })]))]), translate([70.0, 10.0, 0.0], [difference(union(cube({ size: [20.0, 20.0, 4.0], center: false })), translate([10.0, 10.0, -1.0], [cylinder({ height: 6.0, radius: 6.2, center: false })]))]))
  ]
}
