// Generated by OpenSCAD Framework v0.1.0
// Scene: Dispensing Cabinet Control Panel

// Structure: control_panel (PETG)
union() {
  // Substructure: mounting_system
difference() {
  union() {
  // Panel plate
cube([100.0, 60.0, 4.0], center=false);
  // Feature: corner_boss_0
translate([6.0, 6.0, 4.0]) {
  cylinder(h=6.0, r=4.0, center=false);
}
  // Feature: corner_boss_1
translate([94.0, 6.0, 4.0]) {
  cylinder(h=6.0, r=4.0, center=false);
}
  // Feature: corner_boss_2
translate([6.0, 54.0, 4.0]) {
  cylinder(h=6.0, r=4.0, center=false);
}
  // Feature: corner_boss_3
translate([94.0, 54.0, 4.0]) {
  cylinder(h=6.0, r=4.0, center=false);
}
}
  // Feature: corner_hole_0
translate([6.0, 6.0, -1.0]) {
  cylinder(h=12.0, r=1.7, center=false);
}
  // Feature: corner_hole_1
translate([94.0, 6.0, -1.0]) {
  cylinder(h=12.0, r=1.7, center=false);
}
  // Feature: corner_hole_2
translate([6.0, 54.0, -1.0]) {
  cylinder(h=12.0, r=1.7, center=false);
}
  // Feature: corner_hole_3
translate([94.0, 54.0, -1.0]) {
  cylinder(h=12.0, r=1.7, center=false);
}
}
  translate([20.0, 45.0, 0.0]) {
  // Substructure: ventilation_system
difference() {
  union() {
  // Vent boss
cube([30.0, 10.0, 4.0], center=false);
}
  // Feature: vent_slot_0
translate([3.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
  // Feature: vent_slot_1
translate([7.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
  // Feature: vent_slot_2
translate([11.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
  // Feature: vent_slot_3
translate([15.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
  // Feature: vent_slot_4
translate([19.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
  // Feature: vent_slot_5
translate([23.0, 5.0, -1.0]) {
  cylinder(h=6.0, r=1.45, center=false);
}
}
}
  translate([70.0, 10.0, 0.0]) {
  // Substructure: cable_routing_system
difference() {
  union() {
  // Grommet boss
cube([20.0, 20.0, 4.0], center=false);
}
  // Feature: cable_grommet_hole
translate([10.0, 10.0, -1.0]) {
  cylinder(h=6.0, r=6.2, center=false);
}
}
}
}