"""
Elephant Walk - All parts laid out side by side.

This is a special "meta-part" that imports and displays all other parts
in a grid layout, useful for previewing the entire parts library at once.
"""

from __future__ import annotations

import re
from pathlib import Path

from .base import BasePart
from .skeleton import ROOT

# Matches the `import("<subdir>/<name>.stl")` lines the generator writes.
_IMPORT_RE = re.compile(r'import\("([^"]+)"\)')


class ElephantWalkPart(BasePart):
    """The parts-library preview, assembled from every other part's STL.

    Unlike every other part, this one's source is not self-contained: it is
    generated by `apothecary parts elephant-walk` and `import()`s the STL of
    each sibling part by relative path. Those STLs are build artifacts --
    `.gitignore` excludes `*.stl`, and none are tracked -- so on a fresh
    checkout the imports resolve to nothing and OpenSCAD exits 1.

    It therefore reports the same capability check gridfinity uses, so callers
    and tests can tell "not built yet" apart from "broken".
    """

    def missing_imports(self) -> list[str]:
        """Relative paths this .scad imports that are not on disk."""
        if not self.source_file.exists():
            return []
        base = self.source_file.parent
        text = self.source_file.read_text(encoding="utf-8", errors="replace")
        return [ref for ref in _IMPORT_RE.findall(text) if not (base / ref).exists()]

    def can_generate_stl(self) -> tuple[bool, str]:
        """Check whether every imported sibling STL has been rendered."""
        missing = self.missing_imports()
        if missing:
            shown = ", ".join(missing[:3])
            more = f" (+{len(missing) - 3} more)" if len(missing) > 3 else ""
            return False, (
                f"{len(missing)} referenced part STL(s) not rendered yet: {shown}{more}. "
                "Run: apothecary parts elephant-walk --ensure-stl"
            )
        return True, "All referenced part STLs present"


def create(metadata_root: Path) -> BasePart:
    """Create the elephant walk part instance."""
    scad = metadata_root / "parts" / "elephant_walk.scad"
    return ElephantWalkPart(
        name="elephant_walk",
        source_file=scad,
        description="All parts laid out side by side for preview",
        category="utility",
        tags=["preview", "all", "gallery", "utility"],
    )


DEFAULT = create(ROOT)
